export type CuisineSeed = [string, number, string | null, string, string, string[]];

export const CUISINES: CuisineSeed[] = [
  // L1
  ["asia", 1, null, "亚洲", "Asia", []],
  ["europe", 1, null, "欧洲", "Europe", []],
  ["north-america", 1, null, "北美洲", "North America", []],
  ["south-america", 1, null, "南美洲", "South America", []],
  // L2
  ["east-asia", 2, "asia", "东亚", "East Asia", []],
  ["southeast-asia", 2, "asia", "东南亚", "Southeast Asia", []],
  ["south-asia", 2, "asia", "南亚", "South Asia", []],
  ["south-europe", 2, "europe", "南欧", "Southern Europe", []],
  ["west-europe", 2, "europe", "西欧", "Western Europe", []],
  ["n-america", 2, "north-america", "北美区", "North American Mainland", []],
  ["andes", 2, "south-america", "安第斯", "Andes", []],
  // L3
  ["china", 3, "east-asia", "中国", "China", []],
  ["japan", 3, "east-asia", "日本", "Japan", []],
  ["thailand", 3, "southeast-asia", "泰国", "Thailand", []],
  ["india", 3, "south-asia", "印度", "India", []],
  ["italy", 3, "south-europe", "意大利", "Italy", []],
  ["greece", 3, "south-europe", "希腊", "Greece", []],
  ["france", 3, "west-europe", "法国", "France", []],
  ["mexico", 3, "n-america", "墨西哥", "Mexico", []],
  ["peru", 3, "andes", "秘鲁", "Peru", []],
  // L4
  ["sichuan", 4, "china", "川菜", "Sichuan Cuisine", []],
  ["yuecai", 4, "china", "粤菜", "Cantonese Cuisine", []],
  ["kansai", 4, "japan", "关西料理", "Kansai Cuisine", []],
  ["thai-north", 4, "thailand", "泰北菜", "Northern Thai Cuisine", []],
  ["north-indian", 4, "india", "北印菜", "North Indian Cuisine", []],
  ["toscana", 4, "italy", "托斯卡纳菜", "Tuscan Cuisine", []],
  ["provence", 4, "france", "普罗旺斯菜", "Provençal Cuisine", ["mediterranean"]],
  ["oaxaca", 4, "mexico", "瓦哈卡菜", "Oaxacan Cuisine", ["latam"]],
  ["crete", 4, "greece", "克里特菜", "Cretan Cuisine", ["mediterranean"]],
  ["lima", 4, "peru", "利马菜", "Limeño Cuisine", ["latam"]],
  ["uk", 3, "west-europe", "英国", "United Kingdom", []],
  ["spain", 3, "south-europe", "西班牙", "Spain", []],
  ["korea", 3, "east-asia", "韩国", "South Korea", []],
  ["pakistan", 3, "south-asia", "巴基斯坦", "Pakistan", []],
  ...([
    ["hunan", "湖南 · 湘菜", "Hunan"], ["shandong", "山东 · 鲁菜", "Shandong"],
    ["fujian", "福建 · 闽菜", "Fujian"], ["anhui", "安徽 · 徽菜", "Anhui"],
    ["jiangsu", "江苏 · 苏菜", "Jiangsu"], ["zhejiang", "浙江 · 浙菜", "Zhejiang"],
    ["dongbei", "东北家常", "Northeast China"], ["shaanxi", "陕西风味", "Shaanxi"],
    ["henan", "河南 · 豫菜", "Henan"], ["xinjiang", "新疆风味", "Xinjiang"],
    ["guangxi", "广西 · 桂菜", "Guangxi"], ["guizhou", "贵州 · 黔菜", "Guizhou"],
    ["hubei", "湖北 · 鄂菜", "Hubei"], ["beijing", "北京风味", "Beijing"],
    ["chaoshan", "广东 · 潮汕", "Chaoshan"], ["taiwan", "台湾风味", "Taiwan"],
    ["macau", "澳门风味", "Macau"], ["chinese-home", "家常菜 · 不限地区", "Chinese Home Cooking"],
    ["home-baking", "家庭烘焙甜点", "Home Baking"],
  ] as const).map(([id, name, en]): CuisineSeed => [id, 4, "china", name, en, [id]]),
  ["japanese-home", 4, "japan", "日式家庭料理", "Japanese Home Cooking", []],
  ["korean-home", 4, "korea", "韩式家庭料理", "Korean Home Cooking", []],
  ["pakistani-home", 4, "pakistan", "巴基斯坦家常", "Pakistani Home Cooking", []],
  ["british-home", 4, "uk", "英式家常与烘焙", "British Home Cooking", []],
  ["italian-home", 4, "italy", "意式家庭料理", "Italian Home Cooking", ["mediterranean"]],
  ["basque", 4, "spain", "巴斯克风味", "Basque Cuisine", []],
  ["veneto", 4, "italy", "威尼托甜点", "Veneto", []],
];
